version: '3'

services:

  PF-postgres:
    container_name: PF-postgres
    image: postgres:latest
    volumes:
      - ./Vol-PF-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  PF-minio:
    container_name: PF-minio
    image: minio/minio:latest
    volumes:
      - ./Vol-PF-Minio:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
  
  PF-mongodb:
    container_name: PF-mongo
    image: mongo:latest
    volumes:
      - ./Vol-PF-Mongo:/data/db
    ports:
      - 5000:27017

  PF-api:
    container_name: PF_API
    build: .
    image: pf-image:regular
    depends_on:
      - PF-postgres
      - PF-minio
      - PF-mongodb
    env_file:
      - .env
    ports:
      - 3000:3000