version: '3'

services:

  PF-postgres:
    container_name: PF-postgres
    image: postgres:latest
    volumes:
      - ./Vol-PF-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  PF-minio:
    container_name: PF-minio
    image: minio/minio:latest
    volumes:
      - ./Vol-PF-Minio:/data
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: 'minioadmin'
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
  
  PF-mongodb:
    container_name: PF-mongo
    image: mongo:latest
    volumes:
      - ./Vol-PF-Mongo:/data/db
    ports:
      - '5000:27017'

  # PF-api:
  #   container_name: PF-api
  #   image: ...
  #   environment:
  #     DB_File_Upload_HOST: PF-db-file-upload
  #     DB_Metadata_Extractor_HOST: PF-db-metadata-extractor
  #     DB_Page_Splitter_HOST: PF-db-page-splitter
  #     DB_Text_Extractor_HOST: PF-db-text-extractor
  #     DB_File_Upload_PORT: 5001
  #     DB_Metadata_Extractor_PORT: 5002
  #     DB_Page_Splitter_PORT: 5003
  #     DB_Text_Extractor_PORT: 5004
  #     DB_File_Upload_NAME: file_upload
  #     DB_Metadata_Extractor_NAME: metadata_extractor
  #     DB_Page_Splitter_NAME: page_splitter
  #     DB_Text_Extractor_NAME: text_extractor
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     LOG_LEVEL: DEBUG
  #   depends_on:
  #     - PF-db-file-upload
  #     - PF-db-metadata-extractor
  #     - PF-db-page-splitter
  #     - PF-db-text-extractor
  #   ports:
  #     - 3000:80